### ISSUE TITLE
Sistema do CNPq

### ISSUE THREAD

**Issue by iceoffire** [InovaCPS/busca-lattes#1]
O sistema do CNPq não está facilitando o acesso a informações

**Comment by maurozac** [comment]
[Cartilha_0310684_Lattes_Extrator___Manual_Web_Service_de_Extracao_de_Curriculos.pdf](https://github.com/InovaCPS/busca-lattes/files/2383531/Cartilha_0310684_Lattes_Extrator___Manual_Web_Service_de_Extracao_de_Curriculos.pdf)

Essas são as instruções que a Ouvidoria do CNPq forneceu. Eles usam um protocolo SOAP arcano, da década passada. Tem que ter IPs fixos liberados lá. Já enviamos a documentação faz tempo mas ainda não conseguimos a confirmação da efetiva liberação.

**Comment by maurozac** [comment]
Lucas, já olhou esse projeto?

https://github.com/FabricadeSoftwareUNIVILLE/ExtratorLattesCNPq

**Comment by maurozac** [comment]
Novidade! O acesso ao HML voltou a ser sem captcha! Meu velho código voltou a funcionar: 

https://github.com/Maurozac/CTBr/blob/master/lattes.py

Retorna um dict com um monte de coisas prontas e funciona de qualquer lugar. Basta ter os ids lattes, tipo 0522360394137728, esses a gente baixa internamente com os cpfs dos profs. Mas com essa opção a gente também poderá recuperar o lattes dos parceiros que fornecerem seu id.
